Repository fixplzz/fixplz-FE, pull requests merged in 2023-10, with the labels that each got.

#5 [FEATURE] - [STAT] 관리자용 통계 웹 페이지 구현
  fixplz-web/package-lock.json
  fixplz-web/package.json
  fixplz-web/public/assets/imgs/87be945e657ca80a.png
  fixplz-web/src/App.js
  fixplz-web/src/assets/scss/main-page.scss
  fixplz-web/src/assets/scss/stat-page.scss
  fixplz-web/src/components/board/board.css
  fixplz-web/src/components/board/board.jsx
  fixplz-web/src/components/chart/visit-chart.css
  fixplz-web/src/components/chart/visit-chart.jsx
  fixplz-web/src/components/report/report.css
  fixplz-web/src/components/report/report.jsx
  fixplz-web/src/index.js
  fixplz-web/src/pages/error/error-page.jsx
  fixplz-web/src/pages/main/main-page.jsx
  fixplz-web/src/pages/stat/stat-page.jsx
Labels: 🤍 CSS, ⚙️Settings, 🌈 UI, ✨Page, 🖥️ WEB

#9 [REFACTORING] - [STAT] 파일 위치 변경
  fixplz-web/src/App.js
  fixplz-web/src/admin/assets/scss/main-page.scss
  fixplz-web/src/admin/assets/scss/stat-page.scss
  fixplz-web/src/admin/components/board/board.css
  fixplz-web/src/admin/components/board/board.jsx
  fixplz-web/src/admin/components/chart/visit-chart.css
  fixplz-web/src/admin/components/chart/visit-chart.jsx
  fixplz-web/src/admin/components/report/report.css
  fixplz-web/src/admin/components/report/report.jsx
  fixplz-web/src/admin/pages/error/error-page.jsx
  fixplz-web/src/admin/pages/main/main-page.jsx
  fixplz-web/src/admin/pages/stat/stat-page.jsx
Labels: 🧞‍♀️ Refactoring

#10 setting: 환경 세팅, GlobalStyle도입
  fixplz-web/package-lock.json
  fixplz-web/package.json
  fixplz-web/public/assets/imgs/mainlogo.png
  fixplz-web/public/index.html
  fixplz-web/src/App.js
  fixplz-web/src/admin/pages/main/main-page.jsx
  fixplz-web/src/assets/fonts/Pretendard-Black.woff
  fixplz-web/src/assets/fonts/Pretendard-ExtraBold.woff
  fixplz-web/src/assets/fonts/Pretendard-ExtraLight.woff
  fixplz-web/src/assets/fonts/Pretendard-Light.woff
  fixplz-web/src/assets/fonts/Pretendard-Medium.woff
  fixplz-web/src/assets/fonts/Pretendard-Regular.woff
  fixplz-web/src/assets/fonts/Pretendard-SemiBold.woff
  fixplz-web/src/assets/fonts/Pretendard-Thin.woff
  fixplz-web/src/assets/fonts/fonts.css
  fixplz-web/src/assets/styles/global-styles.js
  fixplz-web/src/index.js
  fixplz-web/src/users/asset/image/webmainlogo.svg
  fixplz-web/src/users/pages/template-page/template-page.jsx
  fixplz-web/webpack.config.js
Labels: ⚙️Settings
